# Development environment
# Start with:
# docker compose --file docker-compose.dev.yml up --build

services:
  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    init: true
    ports: [ 5173:5173 ]
    env_file: [ .env ]
    volumes:
      - ./web/node_modules:/app/node_modules:rw
      - ./web/.svelte-kit:/app/.svelte-kit:rw
      - ./web/src:/app/src:ro
      - ./web/static:/app/static:ro

  garage:
    image: ghcr.io/clayenapps/depot-garage:latest
    build: garage
    expose: [ 3900, 3901, 3903 ]
    env_file: [ .env ]
    volumes:
      - ./garage/garage.toml:/etc/garage.toml:ro
