services:
  proxy:
    image: caddy:2.8-alpine
    ports: [ 80:80, 443:443 ]
    networks: [ public ]
    cap_add: [ NET_ADMIN ]
    restart: unless-stopped
    env_file: [ .env ]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  web:
    image: ghcr.io/clayenapps/depot-web:latest
    build: web
    init: true
    expose: [ 3000 ]
    networks: [ public, internal ]
    restart: unless-stopped
    env_file: [ .env ]
    volumes:
      - data:/data

networks:
  public:
  internal:


volumes:
  caddy_data:
  caddy_config:
  data:
